name: kifdamari
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter
  sqflite: ^2.3.0
  path: ^1.8.3
  file_picker: ^8.0.0
  path_provider: ^2.1.2
  google_fonts: ^6.2.1
  charset_converter: ^2.3.0
  share_plus: ^12.0.2
  flutter_launcher_icons: ^0.13.1
  url_launcher: ^6.3.2
  font_awesome_flutter: ^11.0.0
  hive_flutter: ^1.1.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/appbar_icon.png
    - assets/images/board.png
    - assets/images/icon.png
    - assets/images/initial.png
    - assets/images/pieces/

flutter_launcher_icons:
  android: true
  ios: false
  image_path: "assets/images/icon.png" # 用意した画像のパス
  # # Android用のアダプティブアイコンを設定する場合（推奨）
  # adaptive_icon_background: "#FFFFFF" # 背景色または画像
  # adaptive_icon_foreground: "assets/images/icon_foreground.png" # 前景（駒など）